//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tipo_aporte
    {
        public tbl_tipo_aporte()
        {
            this.tbl_patrocinio_evento = new HashSet<tbl_patrocinio_evento>();
        }
    
        public int tbl_tipo_aporte_id { get; set; }
        public string tbl_tipo_aporte_desc { get; set; }
        public bool tbl_tipo_aporte_activo { get; set; }
    
        public virtual ICollection<tbl_patrocinio_evento> tbl_patrocinio_evento { get; set; }
    }
}
