//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jurado
    {
        public int tbl_jurado_id { get; set; }
        public int tbl_evento_id { get; set; }
        public bool tbl_jurado_activo { get; set; }
    
        public virtual tbl_evento tbl_evento { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
