//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_patrocinio
    {
        public tbl_patrocinio()
        {
            this.tbl_patrocinio_evento = new HashSet<tbl_patrocinio_evento>();
        }
    
        public int tbl_patrocinio_id { get; set; }
        public string tbl_patrocinio_nombre { get; set; }
        public string tbl_patrocinio_correo { get; set; }
        public string tbl_patrocinio_contacto_directo { get; set; }
        public string tbl_patrocinio_celular { get; set; }
        public System.DateTime tbl_patrocinio_fecha_creacion { get; set; }
        public bool tbl_patrocinio_activo { get; set; }
    
        public virtual ICollection<tbl_patrocinio_evento> tbl_patrocinio_evento { get; set; }
    }
}
