//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        public tbl_usuario()
        {
            this.tbl_comentario_evento = new HashSet<tbl_comentario_evento>();
            this.tbl_comentario_proyecto = new HashSet<tbl_comentario_proyecto>();
            this.tbl_equipo_usuario = new HashSet<tbl_equipo_usuario>();
            this.tbl_jurado = new HashSet<tbl_jurado>();
        }
    
        public int tbl_usuario_id { get; set; }
        public string tbl_usuario_correo { get; set; }
        public string tbl_usuario_p_nombre { get; set; }
        public string tbl_usuario_s_nombre { get; set; }
        public string tbl_usuario_p_apellido { get; set; }
        public string tbl_usuario_s_apellido { get; set; }
        public System.DateTime tbl_usuario_fecha_nac { get; set; }
        public string tbl_usuario_celular { get; set; }
        public string tbl_usuario_genero { get; set; }
        public string tbl_usuario_password { get; set; }
        public string tbl_usuario_username { get; set; }
        public string tbl_usuario_ocupacion { get; set; }
        public bool tbl_usuario_activo { get; set; }
        public System.DateTime tbl_usuario_fecha_crea { get; set; }
        public bool tbl_usuario_admin { get; set; }
    
        public virtual ICollection<tbl_comentario_evento> tbl_comentario_evento { get; set; }
        public virtual ICollection<tbl_comentario_proyecto> tbl_comentario_proyecto { get; set; }
        public virtual ICollection<tbl_equipo_usuario> tbl_equipo_usuario { get; set; }
        public virtual ICollection<tbl_jurado> tbl_jurado { get; set; }
    }
}
