//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cat_evento
    {
        public tbl_cat_evento()
        {
            this.tbl_evento = new HashSet<tbl_evento>();
        }
    
        public int tbl_cat_evento_id { get; set; }
        public string tbl_cat_evento_desc { get; set; }
        public bool tbl_cat_evento_activo { get; set; }
    
        public virtual ICollection<tbl_evento> tbl_evento { get; set; }
    }
}
