//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_equipo
    {
        public tbl_equipo()
        {
            this.tbl_equipo_usuario = new HashSet<tbl_equipo_usuario>();
            this.tbl_equipo_evento = new HashSet<tbl_equipo_evento>();
            this.tbl_proyecto = new HashSet<tbl_proyecto>();
        }
    
        public int tbl_equipo_id { get; set; }
        public string tbl_equipo_nombre { get; set; }
        public System.DateTime tbl_equipo_fecha_creacion { get; set; }
        public bool tbl_equipo_activo { get; set; }
        public int tbl_equipo_usuario_admin { get; set; }
    
        public virtual ICollection<tbl_equipo_usuario> tbl_equipo_usuario { get; set; }
        public virtual ICollection<tbl_equipo_evento> tbl_equipo_evento { get; set; }
        public virtual ICollection<tbl_proyecto> tbl_proyecto { get; set; }
    }
}
